#!/usr/bin/env bash

# determine the project directory based on the location of this script
MYSELF="$(basename -- "${BASH_SOURCE[0]}")"
SCRIPTDIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
PROJDIR="$(dirname "${SCRIPTDIR}")"

platforms=all
configs=release

function usage {
	printf "usage: %s [-p mac|web|all]\n" "${MYSELF}"
	exit 1
}

while getopts "p:" option
do
	case "${option}" in
		p)
			platforms="${OPTARG}"
			if [ "${platforms}" != "mac" -a "${platforms}" != "web" -a "${platforms}" != "all" ]
			then
				usage
			fi
			;;
		*)
			usage
			;;
	esac
done
shift $(($OPTIND - 1))

if [ "${platforms}" == "all" ]
then
	platforms="web mac"
fi

for platform in ${platforms}
do
	echo "building platform ${platform}..."
	if [ "${platform}" == "web" ]
	then
		dir="embuild"
	else
		dir="build"
	fi

	cmake --build ${PROJDIR}/${dir} $@
	ret=$?
	if [ ${ret} -ne 0 ]
	then
		exit ${ret}
	fi
done
