#!/usr/bin/env bash

# determine the project directory based on the location of this script
SCRIPTDIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
PROJDIR="$(dirname "${SCRIPTDIR}")"

function findexe {
	exe=$1

	printf "Searching for ${exe}..."
	#for dir in $(echo ${PATH} | sed 's/:/\n/g')
	#do
	#	if [ -x "${dir}/${exe}" ]
	#	then
	#		printf " found at ${dir}\n"
	#		return 0
	#	fi
	#done
	dir=$(/usr/bin/which ${exe} 2>/dev/null)
	if [ "${dir}" == "" ]
	then
		printf " not found!\n"
		return 1
	else
		printf " found at ${dir}\n"
		return 0
	fi
}

findexe cmake || exit 1
findexe emmake   || exit 1

cd "${PROJDIR}"

#options=""
if [ "$1" == "clean" ]
then
	#options="--fresh"
	rm -rf build/*
	rm -rf embuild/*
	shift
fi

cmake ${options} -S . -B build $@
emcmake cmake ${options} -S . -B embuild $@

exit 0
